name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore
      working-directory: ./server
      run: dotnet restore

    - name: Build
      working-directory: ./server
      run: dotnet build
        
    - name: Execute unit tests
      working-directory: ./server/ECSchemaLanguageServer.Tests
      run: dotnet run --disable-logo --output Detailed
